apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flask-app.fullname" . }}
  labels:
    {{- include "flask-app.labels" . | nindent 4 }}
type: Opaque
data:
  secret_key: {{ .Values.secret_key | b64enc | quote }}
  db_password: {{ .Values.db_password | b64enc | quote }}
